// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShadowComputing.Catalog.PersistenceLayer.Context;

#nullable disable

namespace ShadowComputing.Catalog.PersistenceLayer.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    [Migration("20250222124716_shadow-computing_catalog_create_database")]
    partial class shadowcomputing_catalog_create_database
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("shadow-computing")
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ShadowComputing.Catalog.DomainLayer.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasColumnOrder(13);

                    b.Property<DateTime>("DiscontinuedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("discontinued_at")
                        .HasColumnOrder(15);

                    b.Property<string>("EstimatedDeliveryTime")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("estimated_delivery_time")
                        .HasColumnOrder(12);

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("image_url")
                        .HasColumnOrder(5);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active")
                        .HasColumnOrder(18);

                    b.Property<bool>("IsBestSeller")
                        .HasColumnType("bit")
                        .HasColumnName("is_best_seller")
                        .HasColumnOrder(16);

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit")
                        .HasColumnName("is_featured")
                        .HasColumnOrder(17);

                    b.Property<bool>("IsNewArrival")
                        .HasColumnType("bit")
                        .HasColumnName("is_new_arrival")
                        .HasColumnOrder(15);

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(350)
                        .HasColumnType("nvarchar(350)")
                        .HasColumnName("manufacturer")
                        .HasColumnOrder(4);

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("model")
                        .HasColumnOrder(3);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(350)
                        .HasColumnType("nvarchar(350)")
                        .HasColumnName("name")
                        .HasColumnOrder(2);

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("price")
                        .HasColumnOrder(8);

                    b.Property<string>("ReturnPolicy")
                        .IsRequired()
                        .HasMaxLength(350)
                        .HasColumnType("nvarchar(350)")
                        .HasColumnName("return_policy")
                        .HasColumnOrder(7);

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("serial_number")
                        .HasColumnOrder(6);

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int")
                        .HasColumnName("stock_quantity")
                        .HasColumnOrder(9);

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at")
                        .HasColumnOrder(14);

                    b.Property<int>("WarrantyPeriod")
                        .HasColumnType("int")
                        .HasColumnName("warranty_Period")
                        .HasColumnOrder(10);

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("weight")
                        .HasColumnOrder(11);

                    b.HasKey("Id");

                    b.ToTable("products", "shadow-computing");
                });

            modelBuilder.Entity("ShadowComputing.Catalog.DomainLayer.Entities.ProductAdvancedDescription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasColumnOrder(1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description")
                        .HasColumnOrder(7);

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("image_url")
                        .HasColumnOrder(6);

                    b.Property<Guid>("ProductDetailId")
                        .HasMaxLength(40)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("product_detail_id")
                        .HasColumnOrder(3);

                    b.Property<Guid>("ProductId")
                        .HasMaxLength(40)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("product_id")
                        .HasColumnOrder(2);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("title")
                        .HasColumnOrder(4);

                    b.Property<string>("VideoUrl")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("video_url")
                        .HasColumnOrder(7);

                    b.HasKey("Id");

                    b.HasIndex("ProductDetailId");

                    b.ToTable("product_advanced_descriptions", "shadow-computing");
                });

            modelBuilder.Entity("ShadowComputing.Catalog.DomainLayer.Entities.ProductBasicDescription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasColumnOrder(1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description")
                        .HasColumnOrder(7);

                    b.Property<Guid>("ProductDetailId")
                        .HasMaxLength(40)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("product_detail_id")
                        .HasColumnOrder(3);

                    b.Property<Guid>("ProductId")
                        .HasMaxLength(40)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("product_id")
                        .HasColumnOrder(2);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("title")
                        .HasColumnOrder(4);

                    b.HasKey("Id");

                    b.HasIndex("ProductDetailId");

                    b.ToTable("product_basic_descriptions", "shadow-computing");
                });

            modelBuilder.Entity("ShadowComputing.Catalog.DomainLayer.Entities.ProductBrand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasColumnOrder(1);

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("image_url")
                        .HasColumnOrder(4);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name")
                        .HasColumnOrder(3);

                    b.Property<Guid>("ProductId")
                        .HasMaxLength(40)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("product_id")
                        .HasColumnOrder(2);

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("product_brands", "shadow-computing");
                });

            modelBuilder.Entity("ShadowComputing.Catalog.DomainLayer.Entities.ProductComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasColumnOrder(1);

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("comment")
                        .HasColumnOrder(4);

                    b.Property<Guid>("ProductId")
                        .HasMaxLength(40)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("product_id")
                        .HasColumnOrder(2);

                    b.Property<Guid>("UserId")
                        .HasMaxLength(40)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id")
                        .HasColumnOrder(3);

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("product_comments", "shadow-computing");
                });

            modelBuilder.Entity("ShadowComputing.Catalog.DomainLayer.Entities.ProductDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasColumnOrder(1);

                    b.Property<Guid>("ProductId")
                        .HasMaxLength(40)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("product_id")
                        .HasColumnOrder(2);

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("product_details", "shadow-computing");
                });

            modelBuilder.Entity("ShadowComputing.Catalog.DomainLayer.Entities.ProductImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasColumnOrder(1);

                    b.PrimitiveCollection<string>("BigImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("big_image_url")
                        .HasColumnOrder(5);

                    b.Property<Guid>("ProductDetailId")
                        .HasMaxLength(40)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("product_detail_id")
                        .HasColumnOrder(3);

                    b.Property<Guid>("ProductId")
                        .HasMaxLength(40)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("product_id")
                        .HasColumnOrder(2);

                    b.PrimitiveCollection<string>("SmallImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("small_image_url")
                        .HasColumnOrder(4);

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("product_images", "shadow-computing");
                });

            modelBuilder.Entity("ShadowComputing.Catalog.DomainLayer.Entities.ProductSeo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasColumnOrder(1);

                    b.Property<Guid>("ProductId")
                        .HasMaxLength(40)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("product_id")
                        .HasColumnOrder(2);

                    b.Property<string>("SeoDescription")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)")
                        .HasColumnName("seo_description")
                        .HasColumnOrder(4);

                    b.Property<string>("SeoKeywords")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("seo_keywords")
                        .HasColumnOrder(5);

                    b.Property<string>("SeoTitle")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("seo_title")
                        .HasColumnOrder(3);

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("product_seos", "shadow-computing");
                });

            modelBuilder.Entity("ShadowComputing.Catalog.DomainLayer.Entities.ProductSpecification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasColumnOrder(1);

                    b.Property<string>("BatteryLife")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("battery_life")
                        .HasColumnOrder(9);

                    b.Property<string>("Display")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("display")
                        .HasColumnOrder(7);

                    b.Property<string>("GraphicsCard")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("graphics_card")
                        .HasColumnOrder(4);

                    b.Property<string>("OperatingSystem")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("operating_system")
                        .HasColumnOrder(8);

                    b.Property<string>("Processor")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("processor")
                        .HasColumnOrder(3);

                    b.Property<Guid>("ProductId")
                        .HasMaxLength(40)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("product_id")
                        .HasColumnOrder(2);

                    b.Property<string>("Ram")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ram")
                        .HasColumnOrder(5);

                    b.Property<string>("Storage")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("storage")
                        .HasColumnOrder(6);

                    b.Property<string>("Weight")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("weight")
                        .HasColumnOrder(10);

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("product_specifications", "shadow-computing");
                });

            modelBuilder.Entity("ShadowComputing.Catalog.DomainLayer.Entities.ProductStandardDescription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasColumnOrder(1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description")
                        .HasColumnOrder(7);

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("image_url")
                        .HasColumnOrder(6);

                    b.Property<Guid>("ProductDetailId")
                        .HasMaxLength(40)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("product_detail_id")
                        .HasColumnOrder(3);

                    b.Property<Guid>("ProductId")
                        .HasMaxLength(40)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("product_id")
                        .HasColumnOrder(2);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("title")
                        .HasColumnOrder(4);

                    b.HasKey("Id");

                    b.HasIndex("ProductDetailId");

                    b.ToTable("product_standard_descriptions", "shadow-computing");
                });

            modelBuilder.Entity("ShadowComputing.Catalog.DomainLayer.Entities.ProductAdvancedDescription", b =>
                {
                    b.HasOne("ShadowComputing.Catalog.DomainLayer.Entities.ProductDetail", "ProductDetail")
                        .WithMany("ProductAdvancedDescriptions")
                        .HasForeignKey("ProductDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductDetail");
                });

            modelBuilder.Entity("ShadowComputing.Catalog.DomainLayer.Entities.ProductBasicDescription", b =>
                {
                    b.HasOne("ShadowComputing.Catalog.DomainLayer.Entities.ProductDetail", "ProductDetail")
                        .WithMany("ProductBasicDescriptions")
                        .HasForeignKey("ProductDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductDetail");
                });

            modelBuilder.Entity("ShadowComputing.Catalog.DomainLayer.Entities.ProductBrand", b =>
                {
                    b.HasOne("ShadowComputing.Catalog.DomainLayer.Entities.Product", "Product")
                        .WithMany("ProductBrands")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ShadowComputing.Catalog.DomainLayer.Entities.ProductComment", b =>
                {
                    b.HasOne("ShadowComputing.Catalog.DomainLayer.Entities.Product", "Product")
                        .WithMany("ProductComments")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ShadowComputing.Catalog.DomainLayer.Entities.ProductDetail", b =>
                {
                    b.HasOne("ShadowComputing.Catalog.DomainLayer.Entities.Product", "Product")
                        .WithMany("ProductDetails")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ShadowComputing.Catalog.DomainLayer.Entities.ProductImage", b =>
                {
                    b.HasOne("ShadowComputing.Catalog.DomainLayer.Entities.Product", "Product")
                        .WithMany("ProductImages")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ShadowComputing.Catalog.DomainLayer.Entities.ProductSeo", b =>
                {
                    b.HasOne("ShadowComputing.Catalog.DomainLayer.Entities.Product", "Product")
                        .WithMany("ProductSeos")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ShadowComputing.Catalog.DomainLayer.Entities.ProductSpecification", b =>
                {
                    b.HasOne("ShadowComputing.Catalog.DomainLayer.Entities.Product", "Product")
                        .WithMany("ProductSpecifications")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ShadowComputing.Catalog.DomainLayer.Entities.ProductStandardDescription", b =>
                {
                    b.HasOne("ShadowComputing.Catalog.DomainLayer.Entities.ProductDetail", "ProductDetail")
                        .WithMany("ProductStandardDescriptions")
                        .HasForeignKey("ProductDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductDetail");
                });

            modelBuilder.Entity("ShadowComputing.Catalog.DomainLayer.Entities.Product", b =>
                {
                    b.Navigation("ProductBrands");

                    b.Navigation("ProductComments");

                    b.Navigation("ProductDetails");

                    b.Navigation("ProductImages");

                    b.Navigation("ProductSeos");

                    b.Navigation("ProductSpecifications");
                });

            modelBuilder.Entity("ShadowComputing.Catalog.DomainLayer.Entities.ProductDetail", b =>
                {
                    b.Navigation("ProductAdvancedDescriptions");

                    b.Navigation("ProductBasicDescriptions");

                    b.Navigation("ProductStandardDescriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
